apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:10.2.0
        securityContext:
          runAsUser: 65534
          runAsGroup: 65534
          allowPrivilegeEscalation: true
          readOnlyRootFilesystem: false
        ports:
        - containerPort: 3000
        env:
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: "admin"
        volumeMounts:
        - name: storage-volume
          mountPath: /var/lib/grafana
        - name: config-volume
          mountPath: /etc/grafana/provisioning/datasources
          readOnly: true
      volumes:
      - name: storage-volume
        persistentVolumeClaim:
          claimName: grafana-pvc
      - name: config-volume
        configMap:
          name: grafana-config

---
# NodePort
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 31000
    targetPort: 3000
  selector:
    app: grafana